export const constanst = {
    languageOptions : [
        {
            value: 'en-US',
            viewValue: 'English'
        },
        {
            value: 'es',
            viewValue: 'Spanish'
        },
        {
            value: 'pt',
            viewValue: 'Portuguese'
        },
        {
            value: 'fr',
            viewValue: 'French'
        },
        {
            value: 'ma',
            viewValue: 'Mandarin'
        },
        {
            value: 'pl',
            viewValue: 'Polish'
        },
        {
            value: 'de',
            viewValue: 'German'
        }
    ],
    english : {
        header : 'If we donot change the world, then who will?',
        subHeader: 'Global Volunteer is a cross-cultural experience for youth who want to gain personal development and leave an impact on the world.',
        experience_new_cultures: 'Experience new cultures',
        experience_new_cultures_des: "There's nothing quite like being in a brand new country, living and volunteering with people from all around. Imagine the things you'd learn!",
        make_your_impact: "Make your impact",
        make_your_impact_des: "You can make a difference in the world, it starts with that first step. Contribute towards the Sustainable Development Goals and tackle the issues you're most passionate about.",
        push_yourself_out: "Push yourself out of your comfort zone",
        push_yourself_out_des: "If you don't try and experience new things, you'll never find your full potential. Challenge yourself, and discover the best version of you.",
        volunteer_header: "Volunteer for the Global Goals",
        volunteer_question: "Why do we provide Global Volunteer experiences?",
        volunteer_question_des: "Our Global Volunteer projects around the world exist because as AIESEC, we choose to shape what we do around what the world needs. We have committed to creating a youth movement to achieve the 17 Sustainable Development Goals by the year 2030.",
        volunteer_question_des1: "This all falls under our Youth 4 Global Goals initiative aimed at activating youth to achieve the Sustainable Development Goals.",
        learn_more : "Learn more",
        video_des : '"When I got here and saw a different reality, it changed me more than I could change them"',
        gain_section_header: "What will you gain?",
        gain_section_des1:"Engage with all kinds of people towards achieving a purpose bigger than yourself. It's how you can empower others.",
        gain_section_des2: "Volunteering abroad isn't easy, but surpassing challenges is what makes it worth it. You learn how to be solution-oriented.",
        gain_section_des3: "Making your contribution and seeing your impact in real-time will show you that you can indeed make a difference the world. Become that world citizen that's needed more than ever.",
        gain_section_des4: "Going beyond what you know opens up new worlds for you. Find your values, explore your passions, and become more self-aware.",
        country_covered: 'Countries covered',
        last_year_experience: 'Last year experiences',
        position_opened: "Positions opened",
        step_header: 'A life-changing experience a few clicks away',
        signup_connect: 'Sign up and connect',
        signup_connect_des: 'Build your profile on the AIESEC Opportunities Portal and we can start matching you with opportunities.',
        search: "Search",
        search_des: "Filter search results to find the perfect opportunity that fits your skills and interests.",
        interview: "Interview",
        interview_des: "Once we find a match, we can start the process of organizing interviews and putting things in place for your internship.",
        confirm_and_go: "Confirm and Go",
        confirm_and_go_des: "Congratulations! You’ll have made it through the interview. From here we’ll get you prepared for your new adventure.",
        features_header: "Feel at ease with our support",
        logistic_support: "Logistics Support",
        logistic_support_des: "We ensure you get the right visa, arrival pick-up information before your experience and departure instructions post-experience.",
        clear_job: "Clear job description",
        clear_job_des: "We accompany you to the workplace on the first day, ensure your job description and goals are clear, and working hours/duration align to the initial description.",
        safe_living_condtion: "Safe living conditions",
        safe_living_condtion_des: "Life and health insurance is mandatory for taking part in AIESEC. You will get information about accommodation and basic living costs.",
        learning_experience: "Learning experience",
        learning_experience_des: "We set clear expectations, provide cultural preparation and facilitate learning spaces before and during experiences.",
        view_opportunity: "View Opportunities",
        AIESEC_des: "AIESEC is a non-governmental not-for-profit organisation in consultative status with the United Nations Economic and Social Council (ECOSOC), affiliated with the UN DPI, member of ICMYO, and is recognized by UNESCO. AIESEC International is registered as a Foundation (Stichting), RSIN #807103895 in Rotterdam, The Netherlands.",
        about: "About",
        about_us: "About us",
        help: "help",
        blog: "Blog",
        press: "Press",
        youth: "Youth",
        global_volunteer: "Global Volunteer",
        global_talent: "Global Talent",
        global_entrepreneur: "Global Entrepreneur",
        youth_speak: "YouthSpeak",
        youth_for_global: "Youth 4 Global Goals",
        oraganization: "Oraganization",
        patner_with_us: "Partner with us",
        perimus_org: "Premium Organization",
        memberships: "Membership",
        join_us: "Join us",
        find_your_country: "Find your Country!",
        alumni: "Alumni",
        cookie_policy: "Cookies policy",
        terms_conditions: "terms & privacy conditions",

            
    },
    spanish : {
        header : 'Si no cambiamos el mundo, entonces Â¿quiÃ©n lo harÃ¡?',
        subHeader: 'Voluntario Global es una experience intercultural para jÃ³venes que quieren obtener desarrollo profesional y hacer impacto en el mundo.',
        experience_new_cultures: 'Experimentar nuevas culturas',
        experience_new_cultures_des: "No hay nada cÃ³mo llegar a un nuevo paÃ­s, vivir y ser voluntario con gente local. Imagina todas las cosas que puedes aprender!",
        make_your_impact: "Haz tu impacto en el mundo",
        make_your_impact_des: "Tu puedes hacer una diferencia en el mundo, todo empieza con ese primer paso. Contribuye a los Objectivos de Desarrollo Sostenible y trabaja en las problemÃ¡ticas que mÃ¡s te apasionan.",
        push_yourself_out: "Sal de tu zona de comfort",
        push_yourself_out_des: "Si no intentas nada nuevo y experimentas nuevas cosas, nunca vas a encontrar tu pleno potencial. RÃ©tate a ti mismo y descubre tu mejor version.",
        volunteer_header: "Voluntario por los Objetivos Globales",
        volunteer_question: "Â¿Por quÃ© ofrecemos experiencias de Voluntariado Global?",
        volunteer_question_des: "Nuestros proyectos de Voluntario Global alrededor del mundo existen por que como AIESEC, decidimos darle forma a lo que hacemos a partir de lo que el mundo necesita. Estamos comprometidos con la creaciÃ³n de un movimiento jÃ³ven para alcanzar los 17 Objectivos de Desarrollo Sostenible para el aÃ±o 2030.",
        volunteer_question_des1: "Todo esto es parte de nuestra iniciativa Youth 4 Global Goals que apunta a activar a la juventud para alcanzar los Objective de Desarrollo Sostenible.",
        learn_more: "Aprende mÃ¡s",
        video_des: '"Cuando lleguÃ© aquÃ­ y vi las diferentes realidades, cambiÃ© mÃ¡s de lo que yo podria cambiar en ellos."',
        gain_section_header: "Â¿QuÃ© ganarÃ¡s?",
        gain_section_des1: "InvolÃºcrate con todos tipo de gente para alcanzar un propÃ³sito mayor. AsÃ­ es como puedes empoderar a otros.",
        gain_section_des2: "Ser voluntario no es fÃ¡cil, pero superar retos es lo que lo hace valioso. AprenderÃ¡s a ser orientado a soluciones.",
        gain_section_des3: "Contribuyendo y viendo en tiempo real el impacto que estÃ¡s haciendo te mostrarÃ¡ que si puedes hacer una diferencia en el mundo. ConviÃ©rtete en el ciudadano global que el mundo necesita mÃ¡s que nunca.",
        gain_section_des4: "Ir mÃ¡s allÃ¡ de lo que conoces abre nuevos mundos para ti. Encuentra tus valores, explora tus pasiones y ten mÃ¡s consciencia de ti mismo.",
        country_covered: 'PaÃ­ses cubiertos',
        last_year_experience: 'Experiencias del aÃ±o pasado',
        position_opened: "Posiciones abiertas",
        step_header: 'Una experiencia que cambiarÃ¡ tu vida a sÃ³lo unos clicks de distancia',
        signup_connect: 'RegÃ­strate y conÃ©ctate',
        signup_connect_des: 'Construye tu perfil en el Portal de Oportunidades de AIESEC y podemos empezar a hacer coincidir tu perfil con oportunidades.',
        search: "Buscar",
        search_des: "Filtra los resultados de bÃºsqueda para encontrar la oportunidad perfecta que se adapte a tus habilidades e intereses.",
        interview: "Entrevista",
        interview_des : "Una vez encontremos un match, podremos iniciar el proceso de entrevistas y de preparaciÃ³n para tu intercambio",
        confirm_and_go: "Confirma y ve",
        confirm_and_go_des: "Â¡Felicitaciones! Lo has logrado en tu entrevista. Desde aquÃ­ te prepararemos para tu nueva aventura.",
        features_header: "SiÃ©ntete cÃ³modo con nuestro apoyo",
        logistic_support: "Soporte logÃ­stico",
        logistic_support_des: "Garantizamos que obtengas la visa correcta, informaciÃ³n sobre el pick-up antes de tu experiencia e instrucciones de salida despuÃ©s de la experiencia.",
        clear_job: "DescripciÃ³n de trabajo clara",
        clear_job_des: "Te acompaÃ±amos en tu primer dÃ­a de trabajo, nos aseguramos que la descripciÃ³n del trabajo y las metas sean claras y adicional que las horas de trabajo y duraciÃ³n del proyecto estÃ©n alineados con la descripciÃ³n inicial. ",
        safe_living_condtion: "Condiciones seguras de vida",
        safe_living_condtion_des: "El seguro mÃ©dico internacional es obligatorio para participar en AIESEC. RecibirÃ¡n informaciÃ³n sobre acomodaciÃ³n y costos bÃ¡sicos de vida.",
        learning_experience: "Experiencia de aprendizaje",
        learning_experience_des: "Establecemos expectativas claras, ofrecemos preparaciÃ³n cultural y facilitamos los espacios de aprendizaje antes y durante las experiencias.",
        view_opportunity: "Ver oportunidades",
        AIESEC_des: "AIESEC es una organizaciÃ³n sin fines de lucro, no gubernamental de carÃ¡cter consultivo con el Consejo Social y EconÃ³mico de las Naciones Unidas (ECOSOC), asociada al Departamento de InformaciÃ³n PÃºblica de las Naciones Unidas, miembro de ICMYO y estÃ¡ reconocida por la UNESCO. AIESEC Internacional estÃ¡ registrada como una FundaciÃ³n (Stichting), RSIN #807103895 en Rotterdam, PaÃ­ses Bajos.",
        about: "Acerca",
        about_us: "Acerca de",
        help: "Ayuda",
        blog: "Blog",
        press: "Prensa",
        youth: "JÃ³venes",
        global_volunteer: "Voluntario Global",
        global_talent: "Talento Global",
        global_entrepreneur: "Emprendedor Global",
        youth_speak: "YouthSpeak",
        youth_for_global: "Youth 4 Global Goals",
        oraganization: "Organizaciones",
        patner_with_us: "Se nuestro aliado",
        perimus_org: "OrganizaciÃ³nes Premium",
        memberships: "MembresÃ­a",
        join_us: "Ãšnete",
        find_your_country: "Â¡Encuentra tu paÃ­s!",
        alumni: "Alumni",
        cookie_policy: "PolÃ­tica de cookies",
        terms_conditions: "tÃ©rminos y condiciones de privacidad",


    },  
    portuguese : {
        header : 'Se eu nÃ£o mudar o mundo, entÃ£o quem vai mudar?',
        subHeader: 'Voluntariado Global Ã© uma experiÃªncia inter-cultural para jovens que querem desenvolver-se pessoalmente e deixar um impacto no mundo.',
        experience_new_cultures: 'Exprimenta novas culturas',
        experience_new_cultures_des: "NÃ£o hÃ¡ nada como estar num paÃ­s novo , viver e fazer voluntariado com pessoas de todo o mundo. Imagina as coisas que podes aprender!",
        make_your_impact: "Deixa o teu impacto no mundo!",
        make_your_impact_des: "Tu podes fazer a diferenÃ§a no mundo, tudo comeÃ§a com aquele primeiro passo. Contribuir para os Objetivos de Desenvolvimento SustentÃ¡vel e abordar os problemas sobre os quais Ã©s mais apaixonado.",
        push_yourself_out: "Sai da tua zona de conforto!",
        push_yourself_out_des: "Se nÃ£o tentares e experimentares coisas novas, nunca encontrarÃ¡s o teu potencial total. Desafia-te e descobre a melhor versÃ£o de ti prÃ³prio.",
        volunteer_header: "Voluntaria-te pelos Objetivos Globais",
        volunteer_question: "Porque proporcionamos experiÃªncias de voluntariado internacional?",
        volunteer_question_des: "Os nossos projetos de Global Volunteer em todo o mundo existem porque, como AIESEC, escolhemos moldar o que fazemos em funÃ§Ã£o do que o mundo precisa. Comprometemo-nos a criar um movimento jovem para atingir os 17 Objetivos de Desenvolvimento SusentÃ¡vel atÃ© 2030.",
        volunteer_question_des1: "Tudo isto se enquadra na nossa iniciativa Youth 4 Global Goals, destinada a motivar os nossos jovens a alcanÃ§ar os Objetivos de Desenvolvimento SustentÃ¡vel.",
        learn_more: "Sabe mais",
        video_des: '"Quando cheguei aqui e  vi uma realidade diferente, isso mudou-me mais a mim do que o que consegui mudar neles! ',
        gain_section_header: "O que vais ganhar?",
        gain_section_des1: "Envolveres-te com todas as pessoas para alcanÃ§ar um propÃ³sito maior do que tu mesmo. Ã‰ assim que consegues desenvolver os outros.",
        gain_section_des2: "Ser voluntÃ¡rio no estrangeiro nÃ£o Ã© fÃ¡cil, mas ultrapassar os desafios Ã© o que faz valer a pena. AprenderÃ¡s a ser orientado para a soluÃ§Ã£o.",
        gain_section_des3: "Dar tua contribuiÃ§Ã£o e ver o teu impacto em tempo real vai mostrar que efetivamente podes fazer diferenÃ§a no mundo. Torna-te o cidadÃ£o do mundo que Ã© mais necessÃ¡rio do que nunca,",
        gain_section_des4: "Ir alÃ©m do que  conheces abre novos mundos para ti. Encontra os teus valores, explora as tuas paixÃµes e torna-te mais consciente de ti prÃ³prio.",
        country_covered: 'PaÃ­ses abrangidos',
        last_year_experience: 'ExperiÃªncias do ano passado',
        position_opened: 'PosiÃ§Ãµes abertas',
        step_header: 'Uma experiÃªncia que mudarÃ¡ a tua vida, apenas a alguns cliques',
        signup_connect: 'Registar e conectar',
        signup_connect_des: 'Cria o teu perfil no Portal de Oportunidades da AIESEC e podemos comeÃ§ar jÃ¡ a encontrar oportunidade para ti.',
        search: "Procurar",
        search_des: "Filtra os resultados da pesquisa para encontrares a oportunidade perfeita que se adapta Ã s tuas habilidades e interesses.",
        interview: "Entrevista",
        interview_des: "Assim que encontrarmos uma correspondente, podemos iniciar o processo de organizar entrevistas e colocar tudo em ordem para o teu estÃ¡gio.",
        confirm_and_go: "Confirma e vai",
        confirm_and_go_des: "ParabÃ©ns! Concluiste a entrevista. A partir daqui, vamos te preparar para tua nova aventura.",
        features_header: "Sente-te Ã  vontade com nosso apoio",
        logistic_support: "Apoio logÃ­stico",
        logistic_support_des: "Garantimos que obtens o visto certo, informaÃ§Ãµes sobre o pick-up na tua chegada antes de tua experiÃªncia e instruÃ§Ãµes da partida apÃ³s a experiÃªncia.",
        clear_job: "DescriÃ§Ã£o clara do trabalho ",
        clear_job_des: "NÃ³s acompanhamos-te ao local de trabalho no primeiro dia, asseguramos-te a descriÃ§Ã£o do trabalho e que os objetivos sejam claros e as horas/duraÃ§Ã£o do trabalho alinhem Ã  descriÃ§Ã£o inicial.",
        safe_living_condtion: "CondiÃ§Ãµes seguranÃ§a de vida",
        safe_living_condtion_des: "Seguro de vida e saÃºde Ã© obrigatÃ³rio para participar na AIESEC. ReceberÃ¡s informaÃ§Ãµes sobre s acomodaÃ§Ã£o e  os custos bÃ¡sicos de vida.",
        learning_experience: "ExperiÃªncia de aprendizagem",
        learning_experience_des: "Definimos expectativas claras, fornecemos preparaÃ§Ã£o cultural e facilitamos espaÃ§os de aprendizagem antes e durante as experiÃªncias.",
        view_opportunity: "Ver oportunidades",
        AIESEC_des: "A AIESEC Ã© uma organizaÃ§Ã£o nÃ£o-governamental sem fins lucrativos com status consultivo junto ao Conselho EconÃ³mico e Social das NaÃ§Ãµes Unidas (ECOSOC), afiliada ao Departamento das NaÃ§Ãµes Unidas, membro do ICMYO, e reconhecida pela UNESCO. A AIESEC International estÃ¡ registada como FundaÃ§Ã£o (Stichting), RSIN # 807103895 em RoterdÃ£o, PaÃ­ses Baixos",
        about: "Sobre",
        about_us: "Sobre nÃ³s",
        help: "Ajuda",
        blog: "Blog",
        press: "Imprensa",
        youth: "Jovens",
        global_volunteer: "Global Volunteer",
        global_talent: "Global Talent ",
        global_entrepreneur: "Global Entrepreneur",
        youth_speak: "YouthSpeak",
        youth_for_global: "Youth 4 Global Goals",
        oraganization: "OrganizaÃ§Ã£o",
        patner_with_us: "Torne-se nosso parceiro!",
        perimus_org: "OrganizaÃ§Ã£o Premium",
        memberships: "Membros",
        join_us: "Junta-te a nÃ³s!",
        find_your_country: "Encontra o teu paÃ­s!",
        alumni: "Alumni",
        cookie_policy: "PolÃ­tica de cookies",
        terms_conditions: "termos e condiÃ§Ãµes de privacidade",

    },  
    french : {
        header : 'Si nous ne changeons pas le monde, alors, qui va le faire?',
        subHeader: 'Global Volunteer est une expÃ©rience interculturelle pour les jeunes qui souhaitent acquÃ©rir un dÃ©veloppement personnel et avoir un impact positive sur le monde.',
        experience_new_cultures: 'DÃ©couvrez de nouvelles cultures',
        experience_new_cultures_des: "Il n'y a rien comme Ãªtre dans un nouveau pays, vivre et faire du bÃ©nÃ©volat avec des gens de tous les coins du monde. Imaginez les choses que vous apprendrez!",
        make_your_impact: "Faites votre impact sur le monde",
        make_your_impact_des: "Vous pouvez faire une diffÃ©rence dans le monde, cela commence par cette premiÃ¨re Ã©tape. Contribuer aux objectifs de dÃ©veloppement durable et aborder les problÃ¨mes dont vous Ãªtes le plus passionnÃ©.",
        push_yourself_out: "Sortez de votre zone de confort",
        push_yourself_out_des: "Si vous n'essayez pas de dÃ©couvrir de nouvelles choses, vous ne trouverez jamais votre plein potentiel. DÃ©fiez-vous, et dÃ©couvrez la meilleure version de votre part.",
        volunteer_header: "BÃ©nÃ©vole pour les objectifs mondiaux",
        volunteer_question: "Pourquoi fournissons-nous des expÃ©riences de bÃ©nÃ©voles internationaux?",
        volunteer_question_des: "Nos projets Global Volunteerdans le monde existent parce que, comme AIESEC, nous choisissons de transformer ce que nous faisons autour de ce que le monde a besoin. Nous nous sommes engagÃ©s Ã  crÃ©er un mouvement de jeunesse pour atteindre les 17 objectifs de dÃ©veloppement durable d'ici l'an 2030.",
        volunteer_question_des1: "Tout cela relÃ¨ve de notre initiative Â«Youth 4 Global GoalsÂ» visant Ã  activer les jeunes pour atteindre les objectifs de dÃ©veloppement durable.",
        learn_more: "Apprenez encore plus",
        video_des: "Quand je suis arrivÃ© ici et j'ai vu une rÃ©alitÃ© diffÃ©rente, cela m'a changÃ© plus que je ne pourrais les changer.",
        gain_section_header: "Qu'allez vous gagner?",
        gain_section_des1: "S'engager avec toutes sortes de personnes pour atteindre un but plus grand que vous. C'est comme Ã§a que vous pouvez responsabiliser les autres.",
        gain_section_des2: "Le bÃ©nÃ©volat Ã  l'Ã©tranger n'est pas facile, mais les dÃ©fis Ã  relever sont ce qui en fait la peine. Vous apprendrez Ã  Ãªtre orientÃ© vers la solution.",
        gain_section_des3: "Faire votre contribution et voir votre impact en temps rÃ©el vous montrera que vous pouvez vraiment faire une diffÃ©rence dans le monde. Devenez ce citoyen mondial dont on a besoin plus que jamais.",
        gain_section_des4: "Au-delÃ  de ce que vous savez, vous ouvrez de nouveaux mondes. Trouvez vos valeurs, explorez vos passions et devenez plus conscient de soi.",
        country_covered: 'Pays couverts',
        last_year_experience: "ExpÃ©riences de l'annÃ©e derniÃ¨re",
        position_opened: 'Positions Disponibles',
        step_header: 'Une expÃ©rience de changement de vie Ã  quelques clics',
        signup_connect: 'Inscrivez-vous et connectez-vous',
        signup_connect_des: "CrÃ©ez votre profil sur le Portail OpportunitÃ©s d'AIESEC et nous pouvons commencer Ã  vous associer Ã  des opportunitÃ©s.",
        search: "Recherche",
        search_des: "Filtrer les rÃ©sultats de recherche pour trouver l'opportunitÃ© parfaite qui correspond Ã  vos compÃ©tences et vos intÃ©rÃªts.",
        interview: "Entretien",
        interview_des: "Une fois que nous trouvons une correspondance, nous pouvons commencer la procÃ©dure d'organisation d'entretiens et de mise en place pour votre stage.",
        confirm_and_go: "Confirmez et S'envolez",
        confirm_and_go_des: "Toutes nos fÃ©licitations! Vous aurez terminÃ© l'entretien. De lÃ , nous vous prÃ©parerons Ã  votre nouvelle aventure.",
        features_header: "Se sentir Ã  l'aise avec notre soutien",
        logistic_support: "Support logistique",
        logistic_support_des: "Nous vous assurons que vous obtenez le bon visa, les informations de collecte d'arrivÃ©e avant votre expÃ©rience et vos instructions de dÃ©part aprÃ¨s l'expÃ©rience.",
        clear_job: "Description de travail claire",
        clear_job_des: "Nous vous accompagnons sur le lieu de travail le premier jour, assurez-vous que la description du poste et les objectifs sont clairs et que les heures de travail / la durÃ©e correspondent Ã  la description initiale.",
        safe_living_condtion: "Conditions de vie en sÃ©curitÃ©",
        safe_living_condtion_des: "L'assurance vie et maladie est obligatoire pour participer Ã  AIESEC. Vous obtiendrez des informations sur l'hÃ©bergement et les coÃ»ts de base de la vie.",
        learning_experience: "ExpÃ©rience d'apprentissage",
        learning_experience_des: "Nous dÃ©finissons des attentes claires, fournissons une prÃ©paration culturelle et facilitons les espaces d'apprentissage avant et pendant les expÃ©riences.",
        view_opportunity: "Afficher les opportunitÃ©s",
        AIESEC_des: "AIESEC est une organisation non gouvernementale avec un statut consultative au Conseil Ã©conomique et social des Nations unies (ECOSOC), affiliÃ© avec le DÃ©partement de l'information des Nations Unies, membre de ICMYO et est reconnu par UNESCO. AIESEC Internationale est rÃ©gistrÃ©e comme une fondation (Stichting), RSIN #807103895 Ã  Rotterdam, les Pays-Bas.",
        about: "A prop",
        about_us: "A propos",
        help: "Aide",
        blog: "Blog",
        press: "Presse",
        youth: "Jeunes",
        global_volunteer: "Global Volunteer",
        global_talent: "Global Talent",
        global_entrepreneur: "Global Entrepreneur",
        youth_speak: "YouthSpeak",
        youth_for_global: "Youth 4 Global Goals",
        oraganization: "Organisation",
        patner_with_us: "Devenir Partenaire",
        perimus_org: "Organisation Premium",
        memberships: "AdhÃ©sion",
        join_us: "Rejoins nous",
        find_your_country: "Trouvez votre pays",
        alumni: "Alumni",
        cookie_policy: "Politique sur les cookies",
        terms_conditions: "termes et conditions de confidentialitÃ©",
    },
    mandarin : {
        header : 'å¦‚æžœä¸æ˜¯æˆ‘ä»¬åŽ»æ”¹å˜ä¸–ç•Œï¼Œé‚£è¿˜æœ‰è°ï¼Ÿ',
        subHeader: 'æµ·å¤–å¿—æ„¿è€…é¡¹ç›®é€šè¿‡ä¸ºé’å¹´äººæä¾›è·¨æ–‡åŒ–äº¤æµä½“éªŒï¼Œæå‡é’å¹´é¢†å¯¼åŠ›å¹¶å¯¹ä¸–ç•Œäº§ç”Ÿç§¯æžçš„å½±å“ã€‚',
        experience_new_cultures: 'ä½“éªŒå…¨æ–°çš„æ–‡åŒ–',
        experience_new_cultures_des: "è®¾æƒ³ä½ åœ¨ä¸€ä¸ªä¸åŒçš„å›½å®¶ã€çŽ¯å¢ƒç”Ÿæ´»ï¼Œå’Œæ¥è‡ªä¸–ç•Œä¸–ç•Œå„åœ°çš„é’å¹´äººä¸€èµ·å¼€å±•å¿—æ„¿æ´»åŠ¨ï¼Œæ‰€æœ‰çš„ä¸€åˆ‡éƒ½å°†æ˜¯ä¸Žä¼—ä¸åŒï¼ä½ å°†èŽ·å¾—æ„æƒ³ä¸åˆ°çš„æˆé•¿ï¼",
        make_your_impact: "ä»¥ä½ ä¹‹åŠ›ï¼Œå½±å“ä¸–ç•Œ",
        make_your_impact_des: "è®©è¿™ä¸ªä¸–ç•Œå˜å¾—ä¸åŒï¼Œä»Žè‡´åŠ›äºŽå¯æŒç»­å‘å±•ç›®æ ‡å¼€å§‹ï¼Œå¹¶ä¸ºä½ æœ€çƒ­åˆ‡å…³æ³¨çš„ç¤¾ä¼šè®®é¢˜åšå‡ºè´¡çŒ®ã€‚",
        push_yourself_out: "è·³å‡ºèˆ’é€‚åœˆ",
        push_yourself_out_des: "å¦‚æžœä½ ä¸å°è¯•æ–°çš„ä½“éªŒï¼Œä½ å°†æ°¸è¿œä¹Ÿæ— æ³•æ‰¾åˆ°è‡ªå·±çš„æžé™ã€‚æŒ‘æˆ˜è‡ªæˆ‘ï¼ŒæŽ¢å¯»ä¸€ä¸ªæœ€å¥½çš„è‡ªå·±ã€‚",
        volunteer_header: "æˆä¸ºå¯æŒç»­å‘å±•ç›®æ ‡å¿—æ„¿è€…",
        volunteer_question: "ä¸ºä»€ä¹ˆæˆ‘ä»¬è¦æä¾›æµ·å¤–å¿—æ„¿è€…ä½“éªŒï¼Ÿ",
        volunteer_question_des: "AIESEC æ ¹æ®è¿™ä¸ªä¸–ç•Œä¹‹æ‰€éœ€ï¼Œåˆ¶å®šå…¶è¡ŒåŠ¨ç›®æ ‡ï¼Œæ‰€ä»¥æˆ‘ä»¬çš„æµ·å¤–å¿—æ„¿è€…é¡¹ç›®åˆ†å¸ƒåœ¨ä¸–ç•Œå„åœ°ã€‚æˆ‘ä»¬æ”¯æŒé’å¹´è¿åŠ¨ï¼Œå¸Œæœ›åœ¨2030å¹´ä¹‹å‰è¾¾æˆ17é¡¹å¯æŒç»­å‘å±•ç›®æ ‡ã€‚",
        volunteer_question_des1: "è¿™ä¸€åˆ‡éƒ½åœ¨æˆ‘ä»¬çš„â€œé’å¹´çŒ®åŠ›å¯æŒç»­ç›®æ ‡â€è®¡åˆ’ä¹‹ä¸‹ï¼Œæ—¨åœ¨æ¿€åŠ±é’å¹´å®žçŽ°å¯æŒç»­å‘å±•ç›®æ ‡ã€‚",
        learn_more: "äº†è§£æ›´å¤š",
        video_des: "â€œå½“æˆ‘æ¥åˆ°è¿™é‡Œï¼Œçœ‹åˆ°å®Œå…¨ä¸åŒçš„ä¸–ç•Œï¼Œå®ƒå¯¹æˆ‘å¸¦æ¥çš„æ”¹å˜è¿œè¿œå¤§äºŽæˆ‘å¸¦ç»™ä»–ä»¬çš„ã€‚â€",
        gain_section_header: "ä½ å°†æ”¶èŽ·ä»€ä¹ˆï¼Ÿ",
        gain_section_des1: "å½“ä½ ä¸»åŠ¨å¸¦åŠ¨å…¶ä»–äººä¸€èµ·åŽ»å®žçŽ°ä¸€ä¸ªä¸ªäººæ— æ³•æ‰¿æ‹…çš„ç†æƒ³çš„æ—¶å€™ï¼Œä½ å­¦ä¼šäº†å¦‚ä½•æ¿€åŠ±å…¶ä»–äººã€‚",
        gain_section_des2: "åœ¨å›½å¤–åšå¿—æ„¿è€…å¹¶ä¸è½»æ¾ï¼Œä½†è¿™ç§è¶…è¶Šè‡ªæˆ‘çš„æŒ‘æˆ˜æ˜¯å€¼å¾—çš„ã€‚ ä½ å°†å­¦ä¹ å¦‚ä½•æˆä¸ºä¸€ä¸ªä»¥è§£å†³é—®é¢˜ä¸ºå¯¼å‘çš„äººã€‚",
        gain_section_des3: "å½“ä½ è´¡çŒ®å‡ºä½ çš„ä¸€ä»½åŠ›å¹¶ä¸”çœ‹åˆ°äº†åŠæ—¶çš„æ”¹å˜ä¸Žå½±å“çš„æ—¶å€™ï¼Œè¿™æ„å‘³ç€ä½ ç¡®å®žæ˜¯åœ¨æ”¹å˜ä¸–ç•Œï¼Œ å¹¶ä¸”æˆä¸ºäº†é‚£ä¸ªç‹¬ä¸€æ— äºŒçš„ä¸–ç•Œå…¬æ°‘ã€‚",
        gain_section_des4: "æŽ¢ç´¢ä½ æœªçŸ¥çš„é¢†åŸŸï¼Œå°†ä¼šä¸ºä½ å¼€è¾Ÿä¸€ä¸ªæ–°çš„ä¸–ç•Œï¼Œå¸®åŠ©ä½ æ‰¾åˆ°ä½ çš„ä»·å€¼è§‚ï¼ŒæŽ¢ç´¢ä½ çš„æ¿€æƒ…æ‰€åœ¨ï¼Œå¹¶æ›´åŠ äº†è§£è‡ªæˆ‘ã€‚",
        country_covered: 'å›½å®¶ä¸Žåœ°åŒº',
        last_year_experience: "å¾€æœŸé¡¹ç›®ä½“éªŒ",
        position_opened: 'é¡¹ç›®æœºä¼š',
        step_header: 'ç‚¹å‡»å¼€å¯ä¸€æ¬¡æ”¹å˜äººç”Ÿçš„ä½“éªŒ',
        signup_connect: 'æ³¨å†Œå¹¶å–å¾—è”ç³»',
        signup_connect_des: "åœ¨ AIESEC å…¨çƒæœºä¼šå¹³å°ä¸Šå®Œå–„ä½ çš„ä¸ªäººèµ„æ–™ï¼Œæˆ‘ä»¬å³å¯å¼€å§‹å¸®ä½ åŒ¹é…é¡¹ç›®ã€‚",
        search: "æŸ¥æ‰¾é¡¹ç›®æœºä¼š",
        search_des: "ç­›é€‰æœç´¢ç»“æžœï¼Œæ‰¾åˆ°é€‚åˆæ‚¨çš„æŠ€èƒ½å’Œå…´è¶£çš„é¡¹ç›®æœºä¼šã€‚",
        interview: "å‚ä¸Žé¢è¯•",
        interview_des: "æ‰¾åˆ°å¯ä»¥åŒ¹é…çš„é¡¹ç›®åŽï¼Œæˆ‘ä»¬å³å¯å¼€å§‹å®‰æŽ’é¢è¯•ï¼Œå¹¶ä¸ºé¡¹ç›®å¼€å§‹å‡†å¤‡ã€‚",
        confirm_and_go: "ç¡®è®¤å‡ºå‘",
        confirm_and_go_des: "æ­å–œï¼ ä½ å·²é€šè¿‡é¢è¯•ã€‚ æˆ‘ä»¬å°†ä¸Žä½ ä¸€èµ·å¼€å§‹æ–°çš„å†’é™©ã€‚",
        features_header: "åœ¨æˆ‘ä»¬çš„ååŠ©ä¸‹è½»æ¾ç”³è¯·",
        logistic_support: "ç‰©èµ„å‡†å¤‡",
        logistic_support_des: "æˆ‘ä»¬å°†ç¡®ä¿ä½ åœ¨å‡ºå‘å‰æ”¶åˆ°æ­£ç¡®çš„ç­¾è¯ä¸ŽæŽ¥æœºä¿¡æ¯ï¼Œå®Œæˆé¡¹ç›®åŽæ”¶åˆ°ç¦»å¢ƒç¨‹åºæŒ‡å¯¼ã€‚",
        clear_job: "æ˜Žç¡®çš„å·¥ä½œèŒè´£",
        clear_job_des: "æˆ‘ä»¬ä¼šåœ¨ç¬¬ä¸€å¤©é™ªä½ å‰å¾€å·¥ä½œåœ°ç‚¹ï¼Œç¡®ä¿æ•´ä¸ªé¡¹ç›®æœ‰æ¸…æ™°æ˜Žç¡®çš„æè¿°å’Œç›®æ ‡ï¼Œå·¥ä½œæ—¶é—´ / æŒç»­æ—¶é—´ä¸Žæè¿°ä¸€è‡´ã€‚",
        safe_living_condtion: "å®‰å…¨çš„ç”Ÿæ´»æ¡ä»¶",
        safe_living_condtion_des: "å‚ä¸Ž AIESEC äº¤æµé¡¹ç›®æ—¶ï¼Œæ‚¨å¿…é¡»æ‹¥æœ‰å¥åº·ä¿é™©ã€‚ åŒæ—¶ï¼Œæ‚¨ä¹Ÿå°†èŽ·å¾—æœ‰å…³ä½å®¿å’ŒåŸºæœ¬ç”Ÿæ´»è´¹ç”¨çš„ä¿¡æ¯ã€‚",
        learning_experience: "å……å®žçš„å­¦ä¹ ä½“éªŒ",
        learning_experience_des: "æˆ‘ä»¬åˆ¶å®šæ˜Žç¡®çš„æœŸæœ›ç›®æ ‡ï¼Œæä¾›æ–‡åŒ–äº¤æµå‡†å¤‡ï¼Œå¹¶åœ¨é¡¹ç›®å¼€å±•ä¹‹å‰å’ŒæœŸé—´å¼•å¯¼å­¦ä¹ ã€‚",
        view_opportunity: "æŸ¥çœ‹æ›´å¤šé¡¹ç›®æœºä¼š",
        AIESEC_des: "AIESECæ˜¯ä¸€ä¸ªåœ¨è”åˆå›½ç»æµŽåŠç¤¾ä¼šç†äº‹ä¼š(ECOSOC)æ‹¥æœ‰å’¨å•†åœ°ä½çš„éžæ”¿åºœæ€§éžç›ˆåˆ©æ€§ç»„ç»‡,éš¶å±žäºŽè”åˆå›½æ–°é—»éƒ¨(UNDPI)ï¼Œæ˜¯å›½é™…é’å¹´ç»„ç»‡åˆä½œä¼š(ICMYO)çš„ä¸€å‘˜,å¹¶è¢«è”åˆå›½æ•™ç§‘æ–‡ç»„ç»‡è®¤å¯ã€‚AIESECå…¨çƒæ€»ä¼šåœ¨è·å…°é¹¿ç‰¹ä¸¹ä»¥ç»„ç»‡(åä¼š)çš„å½¢å¼æ³¨å†Œã€‚",
        about: "å…³ä",
        about_us: "å…³äºŽ",
        help: "å¸®åŠ©",
        blog: "åšå®¢",
        press: "æ–°é—»",
        youth: "é’å¹´é¡¹ç›®",
        global_volunteer: "æµ·å¤–å¿—æ„¿è€…",
        global_talent: "æµ·å¤–å¸¦è–ªå®žä¹ ",
        global_entrepreneur: "æµ·å¤–é’åˆ›å®žä¹ ",
        youth_speak: "é’å¹´å‘å£°",
        youth_for_global: "é’å¹´çŒ®åŠ›å…¨çƒç›®æ ‡",
        oraganization: "ç»„ç»‡åˆä½œ",
        patner_with_us: "åˆä½œæœºæž„",
        perimus_org: "é«˜çº§åˆä½œä¼™ä¼´",
        memberships: "æˆå‘˜",
        join_us: "åŠ å…¥æˆ‘ä»¬",
        find_your_country: "æŸ¥æ‰¾ä½ çš„å›½å®¶ï¼åœ°åŒºï¼",
        alumni: "æ ¡å‹",
        cookie_policy: "Cookie æ”¿ç­–",
        terms_conditions: "ä¿å¯†æ¡æ¬¾å’Œåå®šåŽæ³¨å†Œ",


    },  
    polish : {
        header : 'JeÅ›li my nie zmienimy Å›wiata, kto zrobi to za nas ?',
        subHeader: 'Global Volunteer to miÄ™dzykulturowe doÅ›wiadczenie przeznaczone dla mÅ‚odych ludzi, ktÃ³rzy chcÄ… siÄ™ rozwinÄ…Ä‡ i jednoczeÅ›nie wpÅ‚ynÄ…Ä‡ pozytywnie na Å›wiat.',
        experience_new_cultures: 'Poznaj nowÄ… kulturÄ™',
        experience_new_cultures_des: "Nie ma nic lepszego od mieszkania w caÅ‚kiem nowym dla Ciebie kraju,  poprzez odbywanie  wolontariatu razem z ludÅºmi z rÃ³Å¼nych zakÄ…tw Å›wiata. WyobraÅº sobie rzeczy, ktÃ³rych mÃ³gÅ‚byÅ› siÄ™ nauczyÄ‡ !",
        make_your_impact: "WpÅ‚yÅ„ na otaczajÄ…cy CiÄ™ Å›wiat.",
        make_your_impact_des: "MoÅ¼esz byÄ‡ zmianÄ…, ktÃ³rÄ… chcesz ujrzeÄ‡ w Å›wiecie. Wszystko zaczyna siÄ™ wraz z podjÄ™ciem sÅ‚ynnego pierwszego kroku. PrzyczyÅ„ siÄ™ do speÅ‚niania   CelÃ³w ZrÃ³wnowaÅ¼onego Rozwoju i zmierz siÄ™ z problemami, na  ktÃ³rych najbardziej Ci zaleÅ¼y .",
        push_yourself_out: "WyjdÅº ze swojej strefy komfortu",
        push_yourself_out_des: "JeÅ›li nie sprÃ³bujesz i nie doÅ›wiadczysz nowych rzeczy, nigdy w peÅ‚ni nie wykorzystasz swojego potencjaÅ‚u. Stawiaj sobie wyzwania i odkryj najlepszÄ… wersjÄ™ siebie.",
        volunteer_header: "WyjedÅº na wolontriat by realizowaÄ‡ Cele ZrÃ³wnowaÅ¼onego Rozwoju.",
        volunteer_question: "Dlaczego zapewniamy doÅ›wiadczenie Global Volunteer?",
        volunteer_question_des: "Nasze projekty Global Volunteer sÄ… realizowane na caÅ‚ym Å›wiecie, poniewaÅ¼ jako AIESEC, decydujemy siÄ™ na dopasowywanie naszych dziaÅ‚aÅ„ do obecnych potrzeb Å›wiata. ZobowiÄ…zliÅ›my siÄ™ do stworzenia ruchu , by do 2030 roku zrealizowaÄ‡ 17 CelÃ³w ZrÃ³wnowaÅ¼onego Rozwoju.",
        volunteer_question_des1: "To podchodzi pod naszÄ… inicjatywÄ™ Youth 4 Global Goals, ktÃ³ra ma na celu aktywowanie mÅ‚odych do realizacji CelÃ³w ZrÃ³wnowaÅ¼onego Rozwoju.",
        learn_more: "Dowiedz siÄ™ wiÄ™cej",
        video_des: '"Kiedy tam dotarÅ‚em i zobaczyÅ‚em innÄ… rzeczywistoÅ›Ä‡, zmieniÅ‚a mnie bardziej niÅ¼ ja mogÅ‚em jÄ… zmieniÄ‡."',
        gain_section_header: "Co zyskasz ?",
        gain_section_des1: "ZaangaÅ¼uj siÄ™ w projekt razem z rÃ³Å¼nymi ludÅºmi, by wspÃ³lnie osiÄ…gnÄ…Ä‡ jeden cel. WÅ‚aÅ›nie tak moÅ¼esz motywowaÄ‡ innych do dziaÅ‚ania.",
        gain_section_des2: "Odbywanie wolontariatu za granicÄ… nie jest Å‚atwe, ale podejmowanie wyzwaÅ„ sprawia, Å¼e jest wyjÄ…tkowe. Poprzez to doÅ›wiadczenie, uczysz siÄ™ jak byÄ‡ zorientowanym na rozwiÄ…zania.",
        gain_section_des3: "Podczas wolontariatu bÄ™dziesz w stanie zobaczyÄ‡ rezultaty swojej pracy oraz to, Å¼e naprawdÄ™ moÅ¼esz mieÄ‡ wpÅ‚yw na Å›wiat. ZostaÅ„ z nami obywatelem Å›wiata. ",
        gain_section_des4: "SiÄ™ganie poza grance Twojej wiedzy otwiera przed TobÄ… nowe perspektywy. OdnajdÅº swoje wartoÅ›ci, odkrywaj pasje i staÅ„ siÄ™ bardziej samoÅ›wiadomy.",
        country_covered: 'Kraje partnerskie',
        last_year_experience: 'DoÅ›wiadczenia z ubiegÅ‚ego roku',
        position_opened: 'DostÄ™pne pozycje',
        step_header: 'Od doÅ›wiadczenia zmieniajÄ…cego Å¼ycie dzieli CiÄ™ kilka klikniÄ™Ä‡ myszkÄ… ',
        signup_connect: 'Zaloguj siÄ™ ',
        signup_connect_des: "StwÃ³rz swÃ³j profil na portalu AIESEC i zacznij szukaÄ‡ odpowiedniej oferty.",
        search: "Wyszukaj",
        search_des: "Filtruj wyniki aby znaleÅºÄ‡ najlepszÄ… ofertÄ™ dopasowanÄ… do Twoich zdolnoÅ›ci i zainteresowaÅ„",
        interview: "Rozmowa rekrutacyjna",
        interview_des: "Kiedy znajdziemy dopasowanÄ… do Ciebie ofertÄ™, zaczniemy procedurÄ™ przeprowadzania rozmÃ³w rekrutacyjnych oraz ustalania szczegÃ³Å‚Ã³w dotyczÄ…cych miejsca Twojego pobytu podczas odbywania praktyki. ",
        confirm_and_go: "PotwierdÅº i ruszaj",
        confirm_and_go_des:"Gratulacje! PrzeszedÅ‚eÅ› do nastÄ™pnego etapu, jakim jest rozmowa rekrutacyjna. Od tej chwili przygotujemy CiÄ™ do przeÅ¼ycia nowej przygody.",
        features_header: "Poczuj siÄ™ swobodnie z naszym wsparciem",
        logistic_support: "Wsparcie logistyczne",
        logistic_support_des: "Zapewniamy  pomoc w uzyskaniu wizy, informacje dotyczÄ…ce miejsca przyjazdu przed przybyciem oraz wskazÃ³wki  dotyczÄ…ce  powrotu position opened zakoÅ„czeniu doÅ›wiadczenia.",
        clear_job: "Jasny opis obowiÄ…zkÃ³w ",
        clear_job_des: "Towarzyszymy Ci podczas pierwszego dnia w pracy, upewniamy siÄ™ czy  opis obowiÄ…zkÃ³w oraz oczekiwania sÄ… jasne. Sprawdzamy czy godziny pracy sÄ… zgodne z opisem w poczÄ…tkowej ofercie.",
        safe_living_condtion: "Bezpieczne warunki zakwterowania",
        safe_living_condtion_des: "Ubezpieczenie zdrowotne jest obowiÄ…zkowe by wziaÄ‡ udziaÅ‚ w programach oferowanych przez AIESEC. Otrzymasz informacje o podstawowych kosztach zakwaterowania w danym miejscu.",
        learning_experience: "DoÅ›wiadczenie pÅ‚ynÄ…ce z nauki",
        learning_experience_des: "Ustalamy jasne oczekiwania oraz zapewniamy przygotowanie do odnaleziena siÄ™ w kulturze innego kraju. ",
        view_opportunity: "Zobacz Oferty",
        AIESEC_des: "AIESEC to organizacja pozarzÄ…dowa non-profit o statusie konsultacyjnym przy Radzie Gospodarczej i SpoÅ‚ecznej ONZ, powiÄ…zana z Departamentem Informacji Publicznej ONZ, ktÃ³ra jest czÅ‚onkiem ICMYO i jest uznawana przez UNESCO. AIESEC International jest zarejestrowane jako Fundacja (Stichting), RSIN #807103895 w Rotterdamie (Holandia).",
        about: "O na",
        about_us: "O nas",
        help: "Pomoc",
        blog: "Bolg",
        press: "Prasa",
        youth: "MÅ‚odzi",
        global_volunteer: "Global Volunteer",
        global_talent: "Global Talent",
        global_entrepreneur: "Global Entrepreneur",
        youth_speak: "YouthSpeak",
        youth_for_global: "Youth 4 Global Goals",
        oraganization: "Organizacja",
        patner_with_us: "ZostaÅ„ naszym partnerem",
        perimus_org: "GÅ‚Ã³wne Organizacje",
        memberships: "CzÅ‚onkostwo",
        join_us: "DoÅ‚Ä…cz do nas",
        find_your_country: "ZnajdÅº swÃ³j kraj!",
        alumni: "Alumni",
        cookie_policy: "Ciasteczka",
        terms_conditions: "Warunki i PolitykÄ™ prywatnoÅ›ci",
    },  
    german : {
        header : 'Wenn wir nicht die Welt verÃ¤ndern, wer dann?',
        subHeader: 'Global Volunteer ist eine interkulturelle Erfahrung fÃ¼r junge Menschen, die sich persÃ¶nlich weiterentwickeln und etwas Gutes fÃ¼r die Welt tun wollen.',
        experience_new_cultures: 'Entdecke neue Kulturen',
        experience_new_cultures_des: "Nichts ist vergleichbar damit in einem neuen Land zu sein und mit Menschen aus der ganzen Welt zu leben und zu arbeiten. Stell dir all die Dinge vor, die du lernen wirst!",
        make_your_impact: "Mache den Unterschied in der Welt",
        make_your_impact_des: "Du kannst einen Unterschied machen in dieser Welt, es beginnt mit einem ersten Schritt. Leiste deinen Beitrag zu den Sustainable Development Goals und arbeite an Themen, die dich am meisten bewegen.",
        push_yourself_out: "Bringe dich selbst aus deiner Komfortzone",
        push_yourself_out_des: "Wenn du nicht neue Dinge ausprobierst wirst du nie dein volles Potentzial erkennen. Ã„ndere dich selbst und finde dein bestes Ich.",
        volunteer_header: "Freiwilligendienst fÃ¼r die Global Goals",
        volunteer_question: "Warum stellen wir Global Volunteer Erfahrungen zur VerfÃ¼gung? ",
        volunteer_question_des: "Unsere Global Volunteer Projekte auf der ganzen Welt existieren weil wir als AIESEC entschieden haben, dass wir unser Tun nach den BedÃ¼rfnissen unserer Welt richten wollen. Wir haben uns dazu verpflichtet eine Jugendbewegung zu werden, um die 17 Sustainable Development Goals bis 2030 zu erreichen.",
        volunteer_question_des1: "Das alles fÃ¤llt unter die Youth 4 Global Goals Initiative, die es sich zum Ziel macht, junge Menschen dazu zu bewegen sich aktiv fÃ¼r die Sustainable Development Goals einzusetzen.",
        learn_more: "Erfahre mehr",
        video_des: '"Als ich ankam wurde ich mit einer komplett anderen RealitÃ¤t konfrontiert, dies hat mich mehr verÃ¤ndert als ich hÃ¤tte sie verÃ¤ndern kÃ¶nnen."',
        gain_section_header: "Was wirst du bekommen?",
        gain_section_des1: "Interagiere mit allen mÃ¶glichen Menschen, um einen Zweck zu erfÃ¼llen, der viel grÃ¶ÃŸer ist als du selbst. So kannst du andere bestÃ¤rken.",
        gain_section_des2: "Freiwilligendienst im Ausland ist nicht einfach, aber wenn du diese Hindernisse dann Ã¼berwindest, ist es das wert. Du kannst lernen, lÃ¶sungsorientiert zu sein.",
        gain_section_des3: "Deinen Beitrag zu leisten und ihn im wahren Leben zu sehen wird dir zeigen, dass man sehr wohl die Welt verÃ¤ndern kann. Ein WeltbÃ¼rger zu sein ist heute relevanter als je zuvor.",
        gain_section_des4: "Weiter zu gehen als das was du kennst, wird dir neue Welten erÃ¶ffnen. Finde deine persÃ¶nlichen Werte, deine Leidenschaften und werde selbstreflektierter.",
        country_covered: 'Abgedeckte LÃ¤nder',
        last_year_experience: 'Erfahrungen im letzten Jahr',
        position_opened: 'Positionen geÃ¶ffnet',
        step_header: 'Nur ein Mausklick von einer Erfahrung entfernt, die dein Leben verÃ¤ndern wird',
        signup_connect: 'Anmelden und verbinden',
        signup_connect_des: "Erstelle dein Profil auf dem AIESEC Opportunites Portal und wir kÃ¶nnen damit anfangen das richtige Projekt fÃ¼r dich zu finden. ",
        search: "Suche",
        search_des: "Filter deine Suchergebnisse, um die perfekte Opportunity zu finden, die auf deine FÃ¤higkeiten und WÃ¼nsche passt.",
        interview: "Interview",
        interview_des: "Sobald du ein Match gefunden hast, kÃ¶nnen wir mit den Interviews beginnen und alles fÃ¼r dein Praktikum vorzubereiten",
        confirm_and_go: "BestÃ¤tige und leg los",
        confirm_and_go_des: "GlÃ¼ckwunsch! Du hast das Interview gemeistert. Jetzt bereiten wir dich auf dein neues Abenteuer vor.",
        features_header: "Wir unterstÃ¼tzen dich dabei",
        logistic_support: "Logistische UnterstÃ¼tzung",
        logistic_support_des: "Wir stellen sicher, dass du das richtige Visum bekommst, Informationen bezÃ¼glich deiner Abholung bevor deine Erfahrung beginnt und Anweisungen zu deiner Abreise nach deiner Erfahrung. ",
        clear_job: "Genaue Aufgabenbeschreibung",
        clear_job_des: "Wir begleiten dich zu deinem ersten Arbeitstag, versichern, dass das Job Profil und die Praktkumsziele klar sind und dass die Arbeitsstunden den ursprÃ¼nglichen Beschreibungen entsprechen.",
        safe_living_condtion: "Sichere Lebensbedingungen",
        safe_living_condtion_des: "Lebens-und Krankenversicherungen sind nÃ¶tig, um mit AIESEC ins Ausland zu gehen. Du bekommst Informationen Ã¼ber deine Unterkunft und die Lebenshaltungskosten.",
        learning_experience: "Lernumgebung",
        learning_experience_des: "Wir setzen klare Erwartungen, bieten kulturelle Vorbereitung und Workshops vor und wÃ¤hrend deiner Erfahrung.",
        view_opportunity: "Zeige Opportunities",
        AIESEC_des: "AIESEC ist eine Nichtregierungs- und Non-Profit-Organisation mit Beraterstatus bei United Natios Economic and Social Council (ECOSOC), verbunden mit UN DPI, Mitglied von ICMYO und anerkannt von UNESCO. AIESEC Internation ist angemeldet als eine Stifuftung (Stichting), RSIN #807103895 in Rotterdam, die Niederlande.",
        about: "Ãœb",
        about_us: "Ãœber",
        help: "Hilfe",
        blog: "Bolg",
        press: "Presse",
        youth: "Jugend",
        global_volunteer: "Global Volunteer",
        global_talent: "Global Talent",
        global_entrepreneur: "Global Entrepreneur",
        youth_speak: "Youth Speak",
        youth_for_global: "Youth 4 Global Goals",
        oraganization: "Organisation",
        patner_with_us: "Arbeiten Sie mit uns zusammen",
        perimus_org: "Premium Organisationen",
        memberships: "Mitgliedschaft",
        join_us: "Trete bei",
        find_your_country: "Finde dein Land!",
        alumni: "Alumni",
        cookie_policy: "Cookie-Richtlinien",
        terms_conditions: "GeschÃ¤ftsbedingungen und DatenschutzerklÃ¤rung zu"

    },  
}
